-- Update all KY3P fields demo_autofill values from the CSV data
-- This script handles the update in one batch operation

-- First, let's create a temporary table to hold our CSV data
CREATE TEMPORARY TABLE temp_ky3p_fields (
    field_key TEXT,
    demo_autofill TEXT
);

-- Insert all the field mappings from the CSV file
INSERT INTO temp_ky3p_fields (field_key, demo_autofill) VALUES
('externalSystems', 'Our external information systems inventory is updated monthly and validated through automated discovery tools and manual audits.'),
('breachNotification', 'Controllers are promptly notified of privacy data breaches within 24 hours of our organization's awareness, including detailed incident information and remediation steps.'),
('privacyIncidentProcedure', 'Formal procedures are in place for reporting, managing, and responding to privacy-related incidents, ensuring prompt and appropriate actions are taken.'),
('publicPrivacyNotice', 'Privacy notices and policies are publicly accessible at every point where personal data is collected, stored, processed, or transmitted, clearly detailing usage and rights.'),
('privacyLawCompliance', 'Privacy policies and standards are fully compliant with global and regional privacy laws, including GDPR, CCPA, CPPA, and GLBA, supported by regular compliance audits.'),
('processControls', 'Internal process controls are regularly assessed, documented, and improved to ensure they remain effective and aligned with security, privacy, and risk management objectives.'),
('automaticSessionTermination', 'System sessions automatically terminate after a period of inactivity, with timeout settings enforced by technical controls in accordance with our security policy.'),
('securityRiskAssessment', 'Risk assessment methodology identifies, quantifies, and prioritizes security threats and vulnerabilities using consistent criteria across systems and business units.'),
('securityAwareness', 'Security awareness training is mandatory for all employees and contractors, covering threats, secure practices, and incident reporting procedures.'),
('securityResponsibility', 'Security responsibilities are formally documented for all employees, contractors, and third parties, defining clear accountability for data protection.'),
('sensitiveRemovalProtection', 'Protection measures for sensitive information removal include a media sanitization policy with secure wiping, physical destruction, and chain of custody documentation.'),
('passwordComplexity', 'Password complexity requirements include minimum length, diverse character types, expiration periods, and reuse prevention, enforced by technical controls.'),
('accessRevocation', 'Access privileges are revoked within 24 hours of employee or contractor termination, with automated alerts and audit trails to document the process.'),
('passwordStorage', 'Passwords are stored using strong salted hashing and encryption, with access to password databases strictly limited to authorized system administrators.'),
('dataArchivalConfiguration', 'Data archival and storage configurations ensure secure, retrievable archives following a documented data retention policy aligned with regulatory requirements.'),
('dataLocationTracking', 'Cloud data locations are tracked and documented through automated asset management tools and regular manual validations.'),
('dataRetentionDisposal', 'Data retention and disposal procedures comply with legal requirements, using secure deletion methods and maintaining detailed disposal records.'),
('intrusionPrevention', 'Intrusion prevention systems are deployed at network boundaries and critical points, with real-time alert monitoring and regular signature updates.'),
('softwareBOM', 'Software bills of materials (SBOMs) are maintained for all developed applications, including all components, dependencies, and third-party libraries with their versions.'),
('malwareProtection', 'Our malware protection strategy layers multiple solutions including endpoint protection, email filtering, web security, and behavioral monitoring tools.'),
('accessAuthorizationReview', 'User access authorizations are reviewed quarterly by system owners and managers, with formal documentation and audit trails of all changes.'),
('sdlcPolicy', 'Our secure software development lifecycle (SDLC) policy mandates security requirements gathering, threat modeling, secure code reviews, and penetration testing.'),
('incidentManagement', 'Incident management procedures define clear roles, response steps, communication protocols, and post-incident analysis requirements for security events.'),
('employeeTraining', 'Security and privacy training is tailored to job roles, delivered regularly, and validated through knowledge assessments and simulated exercises.'),
('authenticationSystems', 'Authentication systems enforce strong identity verification through multi-factor authentication, with risk-based protocols for sensitive operations.'),
('sdlcIntegration', 'Security is integrated throughout our SDLC through automated testing, code scanning, manual reviews, and security gates at each development phase.'),
('securityCodeReview', 'Code reviews follow standardized security checklists addressing OWASP top risks, with automated and manual processes to identify vulnerabilities.'),
('personalDataMapInventory', 'Personal data mapping and inventory is comprehensive and regularly updated, documenting all data flows, processing activities, and retention periods.'),
('dataBackupMechanisms', 'Data backup mechanisms include encryption, offline storage, automated verification, and regular restoration testing to ensure data availability.'),
('vulnerabilityRemediation', 'Our vulnerability remediation program prioritizes fixes based on severity, exploitation risk, and business impact, with defined SLAs for each risk level.'),
('securityOperations', 'Security operations include continuous monitoring, alert management, incident response, and cross-team collaboration for threat mitigation.'),
('disasterRecovery', 'Disaster recovery procedures are tested annually through simulated exercises, with documented recovery time objectives for critical systems.'),
('contractorRestrictions', 'Contractors face strict access restrictions enforced through technical controls, limited account privileges, and detailed auditing of all activities.'),
('operatorLogs', 'System operator actions are logged with detailed attribution, timestamp information, and protection against modification to support forensic investigations.'),
('antivirusUpdates', 'Antivirus/antimalware solutions are automatically updated daily, with compliance monitoring and remediation for any systems falling behind.'),
('alternativePowerSupply', 'Alternative power supplies for critical systems include UPS units, backup generators, and redundant power feeds with automated failover capabilities.'),
('physicalSecurityMonitoring', 'Physical security monitoring includes 24/7 video surveillance, access logs, intrusion detection, and regular security patrol reviews.'),
('informationDestruction', 'Information destruction follows NIST guidelines for media sanitization, with certificates of destruction and chain of custody documentation.'),
('facilityAccess', 'Facility access controls include multi-factor authentication, visitor management, escort requirements, and detailed access logs for all entry points.'),
('technologyRefreshment', 'Technology refreshment cycles are documented and followed, with proactive replacement planning for hardware and software nearing end-of-life.'),
('assetRetrieval', 'Assets from terminated employees and subcontractors are collected and inventoried on or before their last day, ensuring accurate reconciliation.'),
('backupVerification', 'Backup verification processes include automated integrity checking and quarterly restoration testing to ensure data recoverability.'),
('centralizedAuthentication', 'Centralized account management uses Active Directory and Single Sign-On (SSO) solutions to manage credentials securely, encrypting them both at rest and in transit.'),
('privilegedAccountManagement', 'Privileged accounts are tightly controlled through password vaults, just-in-time access, session recording, and enhanced monitoring.'),
('mobileDeviceSecurity', 'Mobile device security policies enforce encryption, remote wiping capabilities, application controls, and automatic screen locking.'),
('networkSegmentation', 'Network segmentation isolates sensitive systems and data using firewalls, VLANs, and zero-trust architecture principles to limit lateral movement.'),
('sensitiveInformationProtection', 'Sensitive information protection includes data classification, encryption, access controls, and data loss prevention tools across all environments.'),
('secureTransmissionProtection', 'Transmission protection mechanisms include TLS 1.2+, client certificate authentication, and encryption for all sensitive data transfers.'),
('defaultPasswords', 'Default passwords are immediately changed, and unnecessary default accounts are disabled before any system deployment or configuration in production environments.'),
('patchTimeliness', 'Critical security patches are applied within 48 hours of release, with regular vulnerability scanning to verify compliance and coverage.'),
('multiFactorAuthentication', 'Multi-factor authentication is required for all remote access, privileged accounts, and sensitive data access across the organization.'),
('maintenanceNotification', 'System maintenance notifications are provided in advance, with scheduled downtime coordinated across dependent systems to minimize disruption.'),
('securityDevelopmentTraining', 'Developers receive specialized security training covering secure coding practices, common vulnerabilities, and threat modeling techniques.'),
('thirdPartyRiskAssessment', 'Third-party risk assessments are conducted before onboarding, with annual reassessments and continuous monitoring for significant changes.'),
('sessionAuthentication', 'Session authentication controls enforce unique identifiers, secure token management, inactivity timeouts, and termination on logout.'),
('testAndProdData', 'Test and production data are strictly segregated, with test environments using anonymized data and implementing comparable security controls.'),
('assetManagement', 'Asset management processes track the complete lifecycle of hardware and software, from acquisition through secure decommissioning.'),
('baselineSoftware', 'Baseline software configurations are documented, securely implemented, and regularly validated against current security standards.'),
('physicalMediaProtection', 'Physical media containing sensitive information is tracked, encrypted, and stored in secured locations with strict access controls.'),
('inventoryReviewProcess', 'Inventory review processes validate asset completeness quarterly, reconciling detected devices against authorized inventory records.'),
('vulnerabilityMonitoring', 'Vulnerability monitoring includes daily scanning, threat intelligence integration, and automated alerting for new critical vulnerabilities.'),
('redundantSystems', 'Critical system redundancy is built into network infrastructure, storage, and processing resources, with automated failover capabilities.'),
('userAuthenticationAndAccess', 'User authentication and access processes enforce principle of least privilege, with role-based access controls and quarterly reviews.'),
('auditTrailProtection', 'Audit trail protection measures include integrity verification, secure storage, access controls, and retention aligned with compliance requirements.'),
('secureDisposal', 'Secure disposal procedures for media and equipment follow NIST SP 800-88 guidelines, with verification and documentation of all disposal activities.'),
('deviceEncryption', 'Device encryption is enforced through technical controls for all laptops, workstations, and mobile devices accessing corporate resources.'),
('informationCommunicationProtection', 'Information communication protection controls include encryption, data loss prevention, and security gateways for all sensitive data exchanges.'),
('communicationTools', 'Communication tools for security information sharing include encrypted messaging platforms, secure knowledge bases, and collaboration portals.'),
('employeeBackground', 'Employee background verification checks are conducted before hire, varying in depth based on position sensitivity and regulatory requirements.'),
('firmwarePatching', 'Firmware patching processes ensure timely updates for network devices, servers, and IoT equipment based on vulnerability severity.'),
('informationSystemInventory', 'Information system inventory is maintained through automated discovery tools and manual validation processes, updated at least monthly.'),
('securityToolOperations', 'Security tooling operations include continuous monitoring, regular tuning, and integration with incident response workflows for rapid threat mitigation.'),
('policyDevelopment', 'Policy development follows a structured process including risk assessment, stakeholder review, executive approval, and regular evaluation.'),
('changeControl', 'Change control procedures require documented requests, risk assessments, approval workflows, and post-implementation verification of all system changes.'),
('policyReview', 'Security policies undergo documented annual reviews and updates to address emerging threats, technology changes, and regulatory requirements.'),
('environmentSeparation', 'Development, testing, and production environments are logically and physically separated with controlled code promotion processes between environments.'),
('endpointMonitoring', 'Endpoint monitoring tools track system health, security posture, and unusual activities with centralized logging and alerting capabilities.'),
('standardChangeControl', 'All system and operational changes undergo a standardized change control review process, documented and approved through our automated tracking system.'),
('criticalActivity', 'Activities impacting critical systems require enhanced approval, risk assessment, testing, and rollback planning to minimize operational disruption.'),
('enterpriseNetworkMonitoring', 'Network traffic is continuously monitored through IDS/IPS systems, flow analysis, and anomaly detection with 24/7 security operations center oversight.'),
('testingProcess', 'Testing processes cover functionality, security, performance, and integration, with documented test plans and evidence of results before deployment.'),
('softwareLicensing', 'Software licensing compliance is maintained through automated inventory tools, reconciliation processes, and regular audit activities.'),
('dualControl', 'Dual control mechanisms require two authorized individuals to approve and execute high-risk changes or transactions to prevent malicious activities.'),
('configurationStandards', 'Configuration standards are documented for all system types, aligned with industry benchmarks, and verified through automated compliance checking.'),
('documentationAvailability', 'System documentation is maintained in a secure, accessible repository with version control and role-based access for authorized personnel.'),
('continuousIntegration', 'Continuous integration pipelines include automated security testing, quality checks, and compliance validation before code deployment.'),
('systemsIntegrity', 'System integrity is maintained through file integrity monitoring, secure boot processes, and change detection mechanisms.'),
('dataClassificationGovernance', 'Data governance and classification policies define data sensitivity levels, handling requirements, and access control measures across all organizational assets.'),
('administrativePrivilege', 'Administrative privileges are restricted to authorized personnel with a documented business need, with enhanced monitoring and regular revalidation.'),
('employeeIdentification', 'Employee identification methods include unique credentials, physical badges, and biometric verification where appropriate for sensitive areas.'),
('loggingGovernance', 'Logging program governance documents the procedures and standards for capturing, reviewing, and retaining system logs, supporting incident investigations and compliance reporting.'),
('antiFraudGovernance', 'Anti-fraud governance measures include detailed policies, controls, monitoring systems, employee training, and clear reporting procedures.'),
('amlGovernance', 'Our anti-money laundering (AML) governance is documented and enforced through clearly defined procedures, ongoing employee training, and regular compliance checks.'),
('sanctionsGovernance', 'Sanctions compliance governance structure includes documented screening procedures, updated watch lists, and regular compliance verification processes.'),
('policyAcknowledgement', 'Employees must formally acknowledge the acceptable use policy electronically before receiving access to company systems and data.'),
('auditTrailScope', 'Audit logs capture detailed information including user identification, timestamps, activities performed, and affected resources for all security-relevant events.'),
('dataRestoration', 'Data restoration procedures are documented and tested quarterly, with recovery time objectives established for different system criticality levels.'),
('backupFrequency', 'Backup frequency is determined by data criticality, with critical systems backed up continuously through real-time replication or snapshots.'),
('dataLossGovernance', 'Information and data loss prevention governance is documented, with clear policies, detection mechanisms, and periodic training for employees.'),
('criticalServerBackup', 'Critical server backup strategies include full system images, incremental backups, offsite storage, and automated verification processes.'),
('remoteAccessPointSecurity', 'Remote access points are secured with encryption, multi-factor authentication, connection time limits, and continuous monitoring for suspicious activities.'),
('offboardingProcess', 'Offboarding processes include automated access revocation, equipment collection, confidentiality reminders, and a signed departure checklist.'),
('codeReviewStandards', 'Secure code review standards require both automated scanning and manual review focusing on authentication, authorization, data validation, and error handling.'),
('secureServerConfiguration', 'Server security configurations follow CIS benchmarks, with hardening procedures, minimized services, and regular compliance validation.'),
('systemAuditReview', 'System audit log reviews occur daily for critical systems, with automated alerting for suspicious patterns and comprehensive documentation of findings.'),
('changeDocumentation', 'All system changes are documented with detailed descriptions, justification, implementation steps, testing results, and approval records.'),
('remoteAccessVerification', 'Remote access verification includes continuous monitoring, periodic review of successful and failed access attempts, and anomaly investigation.'),
('internalAccessControl', 'Internal access control mechanisms enforce segregation of duties and least privilege principles through role-based access controls and regular entitlement reviews.'),
('incidentResponseTesting', 'Incident response procedures are tested quarterly through tabletop exercises and technical simulations covering various security incident scenarios.'),
('devicesInventory', 'All organization devices are inventoried in a centralized system, with automated discovery tools to detect and reconcile unregistered equipment.'),
('securityTestingSchedule', 'Security assessments follow a documented testing schedule, with vulnerability scanning monthly, penetration testing quarterly, and full security audits annually.'),
('physicalMediaAccessControl', 'Physical media access is restricted through technical controls, storage in secured locations, and detailed tracking of all media movements.'),
('patchManagement', 'Patch management processes include regular scanning, severity-based prioritization, testing, scheduled deployment, and verification of successful application.'),
('passwordManagement', 'Password management solutions enforce complexity requirements, secure storage, rotation policies, and protected distribution of credentials.'),
('trustedSources', 'Software and updates are only installed from verified, trusted sources, with integrity verification before deployment to prevent supply chain attacks.'),
('threatProgramDevelopment', 'Threat intelligence is analyzed and integrated into security operations, with actionable information shared across security teams and documented responses.'),
('networkStandardsGovernance', 'Network security standards documentation covers architecture, access controls, monitoring, incident response, and compliance verification procedures.'),
('auditTrailRetention', 'Audit logs are retained for at least one year, with security-related logs kept longer based on compliance requirements and investigation needs.'),
('operatingSystemConfiguration', 'Operating system configurations follow security best practices with removed unnecessary services, regular patching, and baseline compliance checking.'),
('restrictedLimitedAccess', 'Access to sensitive information is restricted based on job roles and business needs, with all exceptions documented and regularly reviewed.'),
('penetrationTestsExecuted', 'Penetration tests are conducted by qualified third parties at least annually, with findings ranked by severity and tracked through remediation.'),
('applicationAuditTrail', 'Application audit trails capture user activities, data access, and changes to system configurations in tamper-resistant logs.'),
('continuousDeployment', 'Continuous deployment pipelines include automated security testing, policy compliance checks, and approval gates for production releases.'),
('networkProtocols', 'Network protocols are restricted to secure, business-justified services, with regular reviews to identify and disable unnecessary protocols.'),
('mobileDeviceManagement', 'Mobile device management solutions enforce encryption, remote wiping, application controls, and security policy compliance for all corporate devices.'),
('antivirusSystem', 'Antivirus systems are deployed on all endpoints and servers, with centralized management, real-time protection, and automated updates.'),
('systemAvailabilityMonitoring', 'System availability is continuously monitored through automated tools, with alerts for performance degradation and outages.'),
('deviceUpdateProcess', 'Device update processes include automated patching, compliance reporting, and remediation procedures for devices falling behind security baselines.');

-- Now, update the ky3p_fields table with the values from our temporary table
UPDATE ky3p_fields AS kf
SET demo_autofill = tf.demo_autofill
FROM temp_ky3p_fields AS tf
WHERE kf.field_key = tf.field_key;

-- Drop the temporary table when done
DROP TABLE temp_ky3p_fields;

-- Verify a sample of the updates
SELECT field_key, demo_autofill
FROM ky3p_fields
ORDER BY RANDOM()
LIMIT 5;